title: ewelink API PHP
description: A simple API connector for Sonoff / ewelink devices.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pjanisio.github.io/ewelinkApiPhp" # the base hostname & protocol for your site
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude these files from the build process
exclude:
  - .github
  - Gemfile
  - Gemfile.lock

# Directories
includes_dir: ".github/workflows/_includes"
layouts_dir: ".github/workflows/_layouts"

# Enable the GitHub Pages plugin
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
